name: deploy

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn
      - run: yarn lint
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn
      - run: yarn build
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.PUBLIC_IP_ADDRESS }} >> ~/.ssh/known_hosts
      - name: Server deployment
        env:
          DEPLOYER_USERNAME: ${{ secrets.DEPLOYER_USERNAME }}
          PUBLIC_IP_ADDRESS: ${{ secrets.PUBLIC_IP_ADDRESS }}
        run: scp -r ./build/* $DEPLOYER_USERNAME@$PUBLIC_IP_ADDRESS:/var/www/html